language: node_js
os: windows
cache:
  directories:
    - node_modules
    - ~/.npm  
node_js:
  - '12'
git: 
  depth: 3
script: 
  - yarn build
deploy: 
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: SPA-Vanilla
  commit_message: "Deploy del proyecto"
  on:
    branch: SPA-Vanilla